name: Deploy Slack Bolt App to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to JFrog Docker Registry
      uses: docker/login-action@v2
      with:
        registry: trialymloms.jfrog.io
        username: ${{ secrets.JFROG_USERNAME }}
        password: ${{ secrets.JFROG_API_KEY }}

    - name: Build and push Docker image to JFrog
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: trialymloms.jfrog.io/bot-docker/slack-bolt-app:latest
        cache-from: type=registry,ref=trialymloms.jfrog.io/bot-docker/slack-bolt-app:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    
